### PR TITLE
Update Palette Python Script

### PR DESCRIPTION
**Pull request by asmtilde**
Here's what I changed:
- Handled the case when no command-line argument is provided more gracefully.
- Use `argparse` for better command-line argument parsing.
- Correct the indexing issue in the `valid` list.
- Make the script more robust by handling exceptions properly.
- Improve readability and clarity of the code.

Thanks,
- Colack

### CODE REVIEW

**Comment by asmtilde** [comment]
I would recommend running a script test before merging however.

**Review by azphina — COMMENTED** [review]
This is works excellently, but it does remove the file saving itself to the directory of the image it's parsing. Was that intentional?

**Comment by azphina** [comment]
Also, it might be just me, but there is some strange indentation here that isn't present in the actual Raquet.h file.

image

**Comment by asmtilde** [comment]
Sorry, I was basing this off of some other code I've worked on, I did a bit of copying and pasting :sweat_smile:. I'll quickly change that and be on my way, along with fixing indentation.

**Comment by asmtilde** [comment]
@icomiki that should be a fix. Tell me if you need anything else

**Review by azphina — APPROVED** [review]
Looks good! I'll merge it now.

**Pull request merged**
